version: "3.9"
services: 
    activemq: 
        image: rmohr/activemq
        container_name: activemq
        environment: 
            - "TZ=Europe/Amsterdam"
        ports:
            - "61616:61616"
            - "8161:8161"
    myapp:
        build: . 
        container_name: mq-talker
        environment: 
            - "STOMPHOST=activemq"
        ports: 
            - "8080:8080"
        depends_on: 
            - activemq
        restart: always