version: "3.9"
services: 
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        restart: always
    api:
        build: .
        command: sh -c '/wait-for mongo:27017 -- /app/main'
        image: mongo-api:latest
        ports:
            - "8080:8080"
        environment: 
            - "MONGO_URL=mongodb://root:example@mongo:27017/"
        depends_on: 
            - mongo