version: "3.9"
services: 
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        restart: always
    api:
        build: .
        command: sh -c '/wait-for mongo:27017 -- /app/main'
        image: mongo-api:latest
        ports:
            - "8080:8080"
        environment: 
            - "MONGO_HOST=mongo"
            - "MONGO_PORT=27017"
            - "MONGO_USER=root"
            - "MONGO_PASSWORD=example"
            - "MONGO_DATABASE=hw-golang"
        depends_on: 
            - mongo